# Generated by Django 2.1.7 on 2019-10-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creategoogleform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillmodel',
            name='basemodel_ptr',
        ),
        migrations.RemoveField(
            model_name='userdetailmodel',
            name='skills',
        ),
        migrations.AddField(
            model_name='userdetailmodel',
            name='skill',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='SkillModel',
        ),
    ]
